all:
	g++ -std=c++17 -Wall -Wextra -Werror -Wno-long-long -Wno-variadic-macros -fexceptions -O2 -I. -I./include main_calc_coef.cpp -lboost_program_options -o calc_coef
	g++ -std=c++17 -Wall -Wextra -Werror -Wno-long-long -Wno-variadic-macros -fexceptions -O2 -I. -I./include main_recv_shape.cpp -lboost_program_options -o recv_shape
